@UI
@UIVOUCHERBATCHCANCELLATION

Feature: Voucher Batch Cancellation

  Scenario: SUT Cancel batch flows
    When I go to the Home page
    Then the browser is at the Home page

    When I click on the Create Campaign link
    Then the browser is at the Create Campaign page

    When I select "Single Use Transferable" from campaignType
    And I enter a random campaign name
    And I enter the values
      | description | desc_text  |
      | pomOfferId  | pom_id_sut |
      | start       | Sat Jan 01 2000 00:00:00 GMT+0000 (BST) |
      | end         | Sun Jan 01 2090 00:00:00 GMT+0000 (BST) |
      | cap         | 100        |
    And I click the Create Campaign button
    And I wait until the campaign links are displayed
    Then the browser is at the List Campaigns page

    And I click on the campaign we just created
    And I click on the Show Create Vouchers link
    And I enter the values
      | sizeBatch | 100 |
    And I click the Create Voucher Batch button
    And I wait for all voucher batches to complete by refreshing the page
    Then the table has the following headers with corresponding first row values
      | State        | READY        |
      | Generated By | admin        |
      | Cancel Batch | Cancel Batch |
      | Export       | Export       |
      | History      | History      |
      | Vouchers     | 100          |
      | Redeemed     | 0            |
      | History      | History      |
    And the History link is enabled
    And the Export link is enabled
    And the Cancel Batch link is enabled

    When I click on the History link
    Then the browser is at the Voucher Batch History page
    And the audit values are
      | Field | Old value | New value |
      | state | CREATING  | READY     |
      | state | PENDING   | CREATING  |
    

    When I click on the < Back link
    And I wait for the voucher batches to display
    And I click on the Cancel Batch link
    And I click the No button
    And I wait for all voucher batches to complete by refreshing the page
    Then the table has the following headers with corresponding first row values
      | State | READY |
    And the History link is enabled
    And the Export link is enabled
    And the Cancel Batch link is enabled

    When I click on the Cancel Batch link
    And I click the Yes button
    And I wait for all voucher batches to complete by refreshing the page
    Then the table has the following headers with corresponding first row values
      | State | CANCELLED |
    And the History link is enabled
    And the Export link is enabled
    And the Cancel Batch link is disabled

    When I click on the History link
    Then the browser is at the Voucher Batch History page
    And the audit history field state changes from READY to CANCELLED
    And I click on the < Back link
    And I wait for the voucher batches to display

    When I click on the Export link
    And I click on the History link
    Then the browser is at the Voucher Batch History page
    And the audit history field exported changes from doNotCheck to doNotCheck


  Scenario: Gifting Cancel batch flows
    When I go to the Home page
    Then the browser is at the Home page

    When I click on the Create Campaign link
    Then the browser is at the Create Campaign page

    When I select "Gifting" from campaignType
    And I enter a random campaign name
    And I enter the values
      | description | desc_text  |
      | pomOfferId  | pom_id_sut |
      | start       | Sat Jan 01 2000 00:00:00 GMT+0000 (BST) |
      | end         | Sun Jan 01 2090 00:00:00 GMT+0000 (BST) |
      | cap         | 100        |
    And I click the Create Campaign button
    And I wait until the campaign links are displayed
    Then the browser is at the List Campaigns page

    And I click on the campaign we just created
    And I click on the Show Create Vouchers link
    And I enter the values
      | sizeBatch | 100 |
    And I click the Create Voucher Batch button
    And I wait for all voucher batches to complete by refreshing the page
    Then the table has the following headers with corresponding first row values
      | State        | READY        |
      | Generated By | admin        |
      | Cancel Batch | Cancel Batch |
      | Export       | Export       |
      | History      | History      |
      | Vouchers     | 100          |
      | Redeemed     | 0            |
      | History      | History      |
    And the History link is enabled
    And the Export link is enabled
    And the Cancel Batch link is enabled

    When I click on the History link
    Then the browser is at the Voucher Batch History page
    And the audit values are
      | Field | Old value | New value |
      | state | CREATING  | READY     |
      | state | PENDING   | CREATING  |
    And I click on the < Back link
    And I wait for the voucher batches to display

    When I click on the Cancel Batch link
    And I click the No button
    And I wait for all voucher batches to complete by refreshing the page
    Then the table has the following headers with corresponding first row values
      | State | READY |
    And the History link is enabled
    And the Export link is enabled
    And the Cancel Batch link is enabled

    When I click on the Cancel Batch link
    And I click the Yes button
    And I wait for all voucher batches to complete by refreshing the page
    Then the table has the following headers with corresponding first row values
      | State | CANCELLED |
    And the History link is enabled
    And the Export link is enabled
    And the Cancel Batch link is disabled

    When I click on the History link
    Then the browser is at the Voucher Batch History page
    And the audit values are
      | Field | Old value | New value |
      | state | READY     | CANCELLED |
      | state | CREATING  | READY     |
      | state | PENDING   | CREATING  |
    And I click on the < Back link
    And I wait for the voucher batches to display

    When I click on the Export link
    And I wait for "200" milliseconds
    And I click on the History link
    Then the browser is at the Voucher Batch History page
    And the audit history field exported changes from doNotCheck to doNotCheck

